name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main   # o la branch que quieras usar

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Firebase Login CI
      run: firebase ci:version

    - name: Deploy to Firebase Hosting
      run: firebase deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT_ID }}
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
